# dxf_preview_server.py
# Flask server to accept DXF uploads, parse with dxf_parser, and return preview JSON

from flask import Flask, request, jsonify
import os
import tempfile
from app.utils import dxf_parser

app = Flask(__name__)

@app.route('/upload_dxf', methods=['POST'])
def upload_dxf():
    if 'file' not in request.files:
        return jsonify({'error': 'No file part'}), 400
    file = request.files['file']
    if file.filename == '':
        return jsonify({'error': 'No selected file'}), 400
    # Save to a temporary file
    with tempfile.NamedTemporaryFile(delete=False, suffix='.dxf') as tmp:
        file.save(tmp)
        tmp_path = tmp.name
    try:
        result = dxf_parser.parse_dxf(tmp_path)
        preview = result.get('preview')
        if preview is None:
            return jsonify({'error': 'No preview generated by parser'}), 500
        return jsonify({'preview': preview})
    except Exception as e:
        return jsonify({'error': str(e)}), 500
    finally:
        os.unlink(tmp_path)

if __name__ == '__main__':
    app.run(debug=True, port=5001)
