# preview_test_runner.py
# Automatically runs a DXF file through dxf_parser and outputs preview JSON for browser viewing
import os
from app.utils import dxf_parser
import json

def main():
    # Path to a DXF file in Inputs/primary_validation
    dxf_dir = os.path.join(os.path.dirname(__file__), 'Inputs', 'primary_validation')
    # Always use the Mandalorian Star Wars DXF file
    mandalorian_file = 'lDCxP-the-mandalorian-star-wars-figure.dxf'
    dxf_path = os.path.join(dxf_dir, mandalorian_file)
    if not os.path.exists(dxf_path):
        print(f'File not found: {dxf_path}')
        return
    print('Parsing:', dxf_path)
    result = dxf_parser.parse_dxf(dxf_path)
    preview = result.get('preview')
    if not preview:
        print('No preview generated by parser!')
        return
    # Write preview JSON to project root
    out_path = os.path.join(os.path.dirname(__file__), 'latest_preview.json')
    with open(out_path, 'w') as f:
        json.dump(preview, f, indent=2)
    print('Preview JSON written to', out_path)

if __name__ == '__main__':
    main()
