"""Make material and thickness nullable

Revision ID: 92268345bce1
Revises: 20250703_add_cart_uid_orderitem
Create Date: 2025-07-07 09:37:04.663154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92268345bce1'
down_revision = '20250703_add_cart_uid_orderitem'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('material',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('thickness',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_order_item_cart_uid'), ['cart_uid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_cart_uid'))
        batch_op.alter_column('thickness',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('material',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
